UBIFS packer / unpacker
redballoonsecurity/ofrak pull request #173
Opened 2023-01-12 16:08 UTC by kibo-redballoon

**Please describe the changes in your request.**
This PR contributes a UBIFS packer / unpacker and associated tests for OFRAK. It uses [mtd-utils](http://www.linux-mtd.infradead.org/) and [ubireader](https://github.com/jrspruitt/ubi_reader) to perform resource packing and unpacking.

**Anyone you think should look at this, specifically?**
@whyitfor

2023-01-18 17:45 UTC, whyitfor requested changes
Looking good!

See two comments that need to be addressed.

2023-01-18 17:45 UTC, whyitfor commented on ofrak_core/ofrak/core/ubifs.py
> +    Size of logical erase blocks and superblock parameters required for repacking.
Can you make this docstring a declarative sentence about what this is? https://github.com/redballoonsecurity/ofrak/blob/master/ofrak_core/ofrak/core/uimage.py#L193 is a good example.

Also, if you want to describe the dataclasses attributes, you should use the following notation:

```
:ivar min_io_size: minimum number of bytes per transaction (see http://www.linux-mtd.infradead.org/doc/ubi.html#L_min_io_unit)
:ivar leb_size: size of logical erase blocks and superblock parameters required for repacking.
:ivar superblock: A SuberblockNode
``` 

Both of this make the auto-generated docs easier to read, for example: https://ofrak.com/docs/reference/ofrak/core/uimage.html

2023-01-18 17:45 UTC, whyitfor commented on ofrak_core/ofrak/core/ubifs.py
> +    brew_package="",  # This isn't compatible with macos, but there may be an alternative tool to do the bidding.
```suggestion
    brew_package=None,  # This isn't compatible with macos, but there may be an alternative tool to do the bidding.
```
Should be set to None if we don't have one. See https://ofrak.com/docs/reference/ofrak/model/component_model.html#ofrak.model.component_model.ComponentExternalTool.

2023-01-18 22:37 UTC, EdwardLarson requested changes
Update changelog please

2023-01-18 23:33 UTC, EdwardLarson approved these changes

2023-01-19 00:48 UTC, whyitfor requested changes
Docstrings are looking great! 

See one comment about dataclass docstrings.

2023-01-19 00:48 UTC, whyitfor commented on ofrak_core/ofrak/core/ubifs.py
> +    :cvar min_io_size: Minimum number of bytes per I/O transaction (see http://www.linux-mtd.infradead.org/doc/ubi.html#L_min_io_unit)
Have you tested that `cvar` renders correctly in the built docs? I know that `var` and `ivar` both work

I think technically these are not class variables -- it looks like class variables are specifically skipped by dataclass: https://docs.python.org/3/library/dataclasses.html#class-variables. 

Let's just change all of these to `:var ...`?

2023-01-19 16:31 UTC, merged