UBI Packer / Unpacker
redballoonsecurity/ofrak pull request #177
Opened 2023-01-17 15:58 UTC by kibo-redballoon

Please describe the changes in your request.
This PR contributes a UBI packer / unpacker and associated tests for OFRAK. This is still WIP.

Anyone you think should look at this, specifically?
@whyitfor

2023-01-18 22:37 UTC, EdwardLarson requested changes
Update changelog por favor

2023-01-18 23:35 UTC, EdwardLarson approved these changes

2023-01-19 00:50 UTC, whyitfor requested changes
Looks good!

See comment about dataclass docstrings.

2023-01-19 00:50 UTC, whyitfor commented on ofrak_core/ofrak/core/ubi.py
> +    :cvar id: The assigned volume ID within the UBI image
Have you tested that `cvar` renders correctly in the built docs? I know that `var` and `ivar` both work

I think technically these are not class variables -- it looks like class variables are specifically skipped by dataclass: https://docs.python.org/3/library/dataclasses.html#class-variables. 

Let's just change all of these to `:var ...`?

2023-01-19 16:46 UTC, whyitfor approved these changes
LGTM!

2023-01-19 17:08 UTC, merged