Add support for flash with multiple of the same field type in attribute
redballoonsecurity/ofrak pull request #195
Opened 2023-01-30 19:54 UTC by jaredgonzales

**One sentence summary of this PR (This should go in the CHANGELOG!)**
Allows for multiple of the same `FlashField.field_type` within a block format as described by `FlashAttributes`

**Link to Related Issue(s)**
N/A

**Please describe the changes in your request.**
Instead of assuming only one of type DATA or ECC, now will parse each field individually and handle accordingly. This should allow a lot more flexibility to customize for different use cases.

**Anyone you think should look at this, specifically?**
@whyitfor

2023-02-07 17:11 UTC, whyitfor approved these changes

2023-02-07 17:27 UTC, rbs-jacob requested changes

2023-02-07 17:27 UTC, rbs-jacob commented on ofrak_core/CHANGELOG.md
> +  - `FlashOobResourceUnpacker` continues to unpack even it blocks do not perfectly align at end of the `FlashOobResource` (this is useful for real-world flash dumps).
```suggestion
  - `FlashOobResourceUnpacker` continues to unpack even if blocks do not perfectly align at end of the `FlashOobResource` (this is useful for real-world flash dumps).
```

2023-02-08 16:46 UTC, rbs-jacob approved these changes

2023-02-08 22:52 UTC, merged