Refactor run_component to utilize full pjson serialization
redballoonsecurity/ofrak pull request #437
Opened 2024-03-04 12:43 UTC by whyitfor

- [ ] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.

**One sentence summary of this PR (This should go in the CHANGELOG!)**

**Link to Related Issue(s)**

**Please describe the changes in your request.**

**Anyone you think should look at this, specifically?**

2024-08-19 19:38 UTC, rbs-jacob requested changes

2024-08-19 19:38 UTC, rbs-jacob commented on frontend/src/utils/SerializerInputForm.svelte
> +    element = [node["type"], {}];
These feel redundant – `setName` essentially does the assignment that is replicated here.

2024-12-04 22:44 UTC, whyitfor commented on frontend/src/utils/SerializerInputForm.svelte
> +    }
Consider using optional chaining syntax here.

2025-01-09 21:27 UTC, rbs-jacob approved these changes

2025-01-09 21:53 UTC, dannyp303 commented
Something is wrong here, seems like this change has broken Enums in the config serializer. 
https://github.com/user-attachments/assets/39e759dc-6248-49b6-ba61-bfb32769fb2d

2025-01-14 16:16 UTC, dannyp303 requested changes

2025-02-06 17:13 UTC, dannyp303 approved these changes

2025-03-27 21:49 UTC, merged