Use GzipFile python unpacker for speed, fall back on pigz if needed
redballoonsecurity/ofrak pull request #472
Opened 2024-06-04 04:53 UTC by ANogin

- [X ] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.

**One sentence summary of this PR (This should go in the CHANGELOG!)**
Use GzipFile python unpacker for speed, fall back on pigz if needed

**Link to Related Issue(s)**
N/A

**Please describe the changes in your request.**
Back before OFRAK became public we switched to using external gzip, and then later in #79 we switched to pigz. The reason the initial switch to gzip was made is because unlike python gzip, gzip and pigz binaries are willing to accept gzipped data with extra junk at the end as a "warning" (exit code 2, as opposed to exit code 1 for errors). Unfortunately, spawning external processes has nontrivial overhead, and asyncio is not enough to mitigate it. This commit tries a compromise - try `gzip.GzipFile` in python first, then fall back to pigz if BadGzipFile is raise.

**Anyone you think should look at this, specifically?**
@whyitfor

2024-06-04 05:15 UTC, whyitfor commented
Would it make sense to add a benchmark test with this to record the speedup? Perhaps a recursive unpack of a filesystem pulled from http://tinycorelinux.net/15.x/x86/release/ or somewhere else?

We would probably want to find a pytest fixture that can record several runs of one test case, and/or perhaps fail if the execution time exceeds a certain threshold. Alternatively, we just add a fixture that records test duration

2024-06-05 11:15 UTC, whyitfor requested changes
Please update the changelog

2024-06-05 17:48 UTC, ANogin commented
> Please update the changelog

Done.

2024-06-05 18:28 UTC, rbs-jacob commented
Since we're adding fallbacks like this, it probably also makes sense to fall back on `gzip` if `pigz` is not installed. We can be sure that it will be present in Docker images, but it likely will not for people using `pip install` OFRAK.

2024-06-06 02:37 UTC, whyitfor commented
@rbs-jacob, interesting idea re:`gzip`/`pigz`. Implementing that cleanly with our `ComponentExternalTool` setup might take some additional thought. I'm in favor of merging this in for now to get the performance improvement -- if you see value in that as a further change please add an issue.

2024-06-06 02:37 UTC, whyitfor approved these changes

2024-06-06 02:38 UTC, merged