Draft: Refactor `File` to inherit from `GenericBinary`
redballoonsecurity/ofrak pull request #492
Opened 2024-08-21 00:58 UTC by whyitfor

- [ ] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.

**One sentence summary of this PR (This should go in the CHANGELOG!)**

**Link to Related Issue(s)**

**Please describe the changes in your request.**

**Anyone you think should look at this, specifically?**

2025-01-06 19:44 UTC, rbs-jacob requested changes
- [ ] Improve documentation
- [ ] Address suggestions below
- [ ] Changelog entry

2025-01-06 19:44 UTC, rbs-jacob commented on ofrak_core/ofrak/core/magic.py
> +    Identify resourced using three identifier patterns:
```suggestion
    Identify resources using three identifier patterns:
```

2025-01-06 19:44 UTC, rbs-jacob commented on ofrak_core/ofrak/core/magic.py
> +        data_length = min(await resource.get_data_length(), 8)
Why run the raw magic pattern matchers only against the first 8 bytes? I personally think 32 or 64 would be better.

Should it be documented somewhere that matcher functions will only get the first few bytes, and not all of the data? I would find this surprising as a user, and would expect it to be clearly documented somewhere.

2025-01-06 19:44 UTC, rbs-jacob commented on docs/contributor-guide/component/identifier.md
> +When required, it is also possible to write custom identifiers. For an example of this, see [ApkIdentifier][ofrak.core.apk.ApkIdentifier].
We should add more docs here with examples of the other two magic patterns. For example, there are some aspects of the raw bytes pattern matcher that are pretty unintuitive (see comment below).

This is also a good place to add information about when to use patterns and when not to (perhaps pointing to the APK as an example of when the magic pattern thing isn't quite sufficient).

2025-01-07 17:18 UTC, rbs-jacob commented on ofrak_core/ofrak/core/__init__.py
> +from ofrak.core.java import JavaArchive
That's really odd. Worth adding a comment in this file that mentions this so someone in the future has this context.

2025-01-07 19:45 UTC, whyitfor reviewed
@rbs-jacob, thanks for the feedback! I believe I've addressed everything, ready for another review.

2025-01-07 19:45 UTC, whyitfor commented on docs/contributor-guide/component/identifier.md
> +When required, it is also possible to write custom identifiers. For an example of this, see [ApkIdentifier][ofrak.core.apk.ApkIdentifier].
Updated documentation.

2025-01-07 19:48 UTC, whyitfor commented on ofrak_core/ofrak/core/dtb.py
> +    return data == struct.pack("<I", DTB_MAGIC_SIGNATURE)
Updated dtb (https://github.com/redballoonsecurity/ofrak/pull/492/commits/4d95dd277d0e9fe52ea542721ff908f726af9ea8) as well as uf2 (https://github.com/redballoonsecurity/ofrak/pull/492/commits/f79f876723708542a9676ce999a0dcd1b2e01fea)

2025-01-07 21:00 UTC, rbs-jacob requested changes
Two small typos introduced in the last commits. Pending those fixes, any outstanding threads, and the changelog merge conflict resolution, this should be good to go.

2025-01-08 21:24 UTC, rbs-jacob requested changes

2025-01-08 21:24 UTC, rbs-jacob commented on docs/contributor-guide/component/identifier.md
> +    it is run: generally speaking, targeting `GenericBinary` with result in this identifier getting run on the largest
```suggestion
    it is run: generally speaking, targeting `GenericBinary` will result in this identifier getting run on the largest
```

2025-01-08 21:24 UTC, rbs-jacob approved these changes
Looks good to me. Excited about this change!

2025-01-08 23:31 UTC, merged